apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: test-app-paused-scaledobject
  namespace: default
  annotations:
    autoscaling.keda.sh/paused: "true"
spec:
  scaleTargetRef:
    name: test-app-paused
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: cpu
    metricType: Utilization
    metadata:
      value: "50"
