# Temporarily grant admin permissions to the default ServiceAccount (Argo Workflows is in the argo namespace)
# For production see: https://argo-workflows.readthedocs.io/en/latest/service-accounts
kubectl -n argo create rolebinding default-admin --clusterrole=admin --serviceaccount=argo:default

# Get autogenerated Admin password for ArgoCD
kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d

# Deploy the event bus
kubectl apply -n argo-events -f https://raw.githubusercontent.com/argoproj/argo-events/stable/examples/eventbus/native.yaml

# list workflows
argo list

# display details about a workflow
argo get <workflow-name>

# submit a workflow
argo submit <workflow-file.yaml>

# watch workflow progress
argo watch <workflow-name>

# list workflow templates
argo template list

# display logs for workflow pod(s)
argo logs <workflow-name>

# Port forward to the ArgoCD server
kubectl -n argocd port-forward svc/argo-cd-argocd-server 8080:80

# Port forward to the Argo Workflows server
kubectl -n argo port-forward svc/argo-workflows-server 2746:2746

# Port forward to the Argo Events webhook server (for submitting an event to trigger an Argo Workflow)
kubectl -n argo-events port-forward $(kubectl -n argo-events get pod -l eventsource-name=webhook -o name) 12000:12000

# POST to the webhook server to trigger an Argo Workflow - you need to have the above portfowarding running obviously
curl -d '{ "message": "Hello World!" }' -H "Content-Type:application/json" -X POST http://127.0.0.1:12000/webhook-events

# There is a generic Sensor in the cluster that triggers a placeholder "whalesay" cowsay workflow as an example.
# You can see the Sensor and the WorkflowTemplate in the Argo Workflows UI.

# Example Sensors:
# https://github.com/argoproj/argo-events/tree/stable/examples/sensors

# NOTE:
# With some of these examples, kubectl apply doesn't work. If you see the "cannot use generate name with apply", use kubectl create instead.
# Many examples of different workflow templates and workflows here:
# https://github.com/argoproj/argo-workflows/tree/main/examples
