apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: orchestration
  namespace: argocd
spec:
  description: Orchestration services (local)
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
