apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: security
  namespace: argocd
spec:
  description: Security and compliance applications

  # Allow all sources
  sourceRepos:
    - '*'

  # Allow deployment to any namespace
  destinations:
    - namespace: '*'
      server: '*'

  # Allow all resource kinds
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'

  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
